// This file is heavily based on (but not a direct copy of) the source code for .NET Core's libraries, by the .NET Foundation and Contributors.
// The original source code is available on GitHub at https://github.com/dotnet/corefx.
// The source code is licensed under the MIT license: https://github.com/dotnet/corefx/blob/master/LICENSE.TXT.
// This file was automatically generated by a T4 Text Template file (ValueTuple.tt).

using System.Collections;
using System.Collections.Generic;

// ReSharper disable NonReadonlyMemberInGetHashCode
// ReSharper disable once CheckNamespace
namespace System {
	public partial struct ValueTuple {

		/// <summary>Creates a tuple with 1 items.</summary>
		/// <typeparam name="T1">The type of the value tuple's first element.</typeparam>
		/// <param name="item1">The value of the value tuple tuple's first element.</param>
		/// <returns>A new <see cref="ValueTuple{T1}" />.</returns>
		public static ValueTuple<T1> Create<T1>(T1 item1) {
			return new ValueTuple<T1>(item1);
		}

		/// <summary>Creates a tuple with 2 items.</summary>
		/// <typeparam name="T1">The type of the value tuple's first element.</typeparam>
		/// <param name="item1">The value of the value tuple tuple's first element.</param>
		/// <typeparam name="T2">The type of the value tuple's second element.</typeparam>
		/// <param name="item2">The value of the value tuple tuple's second element.</param>
		/// <returns>A new <see cref="ValueTuple{T1, T2}" />.</returns>
		public static ValueTuple<T1, T2> Create<T1, T2>(T1 item1, T2 item2) {
			return new ValueTuple<T1, T2>(item1, item2);
		}

		/// <summary>Creates a tuple with 3 items.</summary>
		/// <typeparam name="T1">The type of the value tuple's first element.</typeparam>
		/// <param name="item1">The value of the value tuple tuple's first element.</param>
		/// <typeparam name="T2">The type of the value tuple's second element.</typeparam>
		/// <param name="item2">The value of the value tuple tuple's second element.</param>
		/// <typeparam name="T3">The type of the value tuple's third element.</typeparam>
		/// <param name="item3">The value of the value tuple tuple's third element.</param>
		/// <returns>A new <see cref="ValueTuple{T1, T2, T3}" />.</returns>
		public static ValueTuple<T1, T2, T3> Create<T1, T2, T3>(T1 item1, T2 item2, T3 item3) {
			return new ValueTuple<T1, T2, T3>(item1, item2, item3);
		}

		/// <summary>Creates a tuple with 4 items.</summary>
		/// <typeparam name="T1">The type of the value tuple's first element.</typeparam>
		/// <param name="item1">The value of the value tuple tuple's first element.</param>
		/// <typeparam name="T2">The type of the value tuple's second element.</typeparam>
		/// <param name="item2">The value of the value tuple tuple's second element.</param>
		/// <typeparam name="T3">The type of the value tuple's third element.</typeparam>
		/// <param name="item3">The value of the value tuple tuple's third element.</param>
		/// <typeparam name="T4">The type of the value tuple's fourth element.</typeparam>
		/// <param name="item4">The value of the value tuple tuple's fourth element.</param>
		/// <returns>A new <see cref="ValueTuple{T1, T2, T3, T4}" />.</returns>
		public static ValueTuple<T1, T2, T3, T4> Create<T1, T2, T3, T4>(T1 item1, T2 item2, T3 item3, T4 item4) {
			return new ValueTuple<T1, T2, T3, T4>(item1, item2, item3, item4);
		}

		/// <summary>Creates a tuple with 5 items.</summary>
		/// <typeparam name="T1">The type of the value tuple's first element.</typeparam>
		/// <param name="item1">The value of the value tuple tuple's first element.</param>
		/// <typeparam name="T2">The type of the value tuple's second element.</typeparam>
		/// <param name="item2">The value of the value tuple tuple's second element.</param>
		/// <typeparam name="T3">The type of the value tuple's third element.</typeparam>
		/// <param name="item3">The value of the value tuple tuple's third element.</param>
		/// <typeparam name="T4">The type of the value tuple's fourth element.</typeparam>
		/// <param name="item4">The value of the value tuple tuple's fourth element.</param>
		/// <typeparam name="T5">The type of the value tuple's fifth element.</typeparam>
		/// <param name="item5">The value of the value tuple tuple's fifth element.</param>
		/// <returns>A new <see cref="ValueTuple{T1, T2, T3, T4, T5}" />.</returns>
		public static ValueTuple<T1, T2, T3, T4, T5> Create<T1, T2, T3, T4, T5>(T1 item1, T2 item2, T3 item3, T4 item4, T5 item5) {
			return new ValueTuple<T1, T2, T3, T4, T5>(item1, item2, item3, item4, item5);
		}

		/// <summary>Creates a tuple with 6 items.</summary>
		/// <typeparam name="T1">The type of the value tuple's first element.</typeparam>
		/// <param name="item1">The value of the value tuple tuple's first element.</param>
		/// <typeparam name="T2">The type of the value tuple's second element.</typeparam>
		/// <param name="item2">The value of the value tuple tuple's second element.</param>
		/// <typeparam name="T3">The type of the value tuple's third element.</typeparam>
		/// <param name="item3">The value of the value tuple tuple's third element.</param>
		/// <typeparam name="T4">The type of the value tuple's fourth element.</typeparam>
		/// <param name="item4">The value of the value tuple tuple's fourth element.</param>
		/// <typeparam name="T5">The type of the value tuple's fifth element.</typeparam>
		/// <param name="item5">The value of the value tuple tuple's fifth element.</param>
		/// <typeparam name="T6">The type of the value tuple's sixth element.</typeparam>
		/// <param name="item6">The value of the value tuple tuple's sixth element.</param>
		/// <returns>A new <see cref="ValueTuple{T1, T2, T3, T4, T5, T6}" />.</returns>
		public static ValueTuple<T1, T2, T3, T4, T5, T6> Create<T1, T2, T3, T4, T5, T6>(T1 item1, T2 item2, T3 item3, T4 item4, T5 item5, T6 item6) {
			return new ValueTuple<T1, T2, T3, T4, T5, T6>(item1, item2, item3, item4, item5, item6);
		}

		/// <summary>Creates a tuple with 7 items.</summary>
		/// <typeparam name="T1">The type of the value tuple's first element.</typeparam>
		/// <param name="item1">The value of the value tuple tuple's first element.</param>
		/// <typeparam name="T2">The type of the value tuple's second element.</typeparam>
		/// <param name="item2">The value of the value tuple tuple's second element.</param>
		/// <typeparam name="T3">The type of the value tuple's third element.</typeparam>
		/// <param name="item3">The value of the value tuple tuple's third element.</param>
		/// <typeparam name="T4">The type of the value tuple's fourth element.</typeparam>
		/// <param name="item4">The value of the value tuple tuple's fourth element.</param>
		/// <typeparam name="T5">The type of the value tuple's fifth element.</typeparam>
		/// <param name="item5">The value of the value tuple tuple's fifth element.</param>
		/// <typeparam name="T6">The type of the value tuple's sixth element.</typeparam>
		/// <param name="item6">The value of the value tuple tuple's sixth element.</param>
		/// <typeparam name="T7">The type of the value tuple's seventh element.</typeparam>
		/// <param name="item7">The value of the value tuple tuple's seventh element.</param>
		/// <returns>A new <see cref="ValueTuple{T1, T2, T3, T4, T5, T6, T7}" />.</returns>
		public static ValueTuple<T1, T2, T3, T4, T5, T6, T7> Create<T1, T2, T3, T4, T5, T6, T7>(T1 item1, T2 item2, T3 item3, T4 item4, T5 item5, T6 item6, T7 item7) {
			return new ValueTuple<T1, T2, T3, T4, T5, T6, T7>(item1, item2, item3, item4, item5, item6, item7);
		}

		/// <summary>Creates a tuple with 8 items.</summary>
		/// <typeparam name="T1">The type of the value tuple's first element.</typeparam>
		/// <param name="item1">The value of the value tuple tuple's first element.</param>
		/// <typeparam name="T2">The type of the value tuple's second element.</typeparam>
		/// <param name="item2">The value of the value tuple tuple's second element.</param>
		/// <typeparam name="T3">The type of the value tuple's third element.</typeparam>
		/// <param name="item3">The value of the value tuple tuple's third element.</param>
		/// <typeparam name="T4">The type of the value tuple's fourth element.</typeparam>
		/// <param name="item4">The value of the value tuple tuple's fourth element.</param>
		/// <typeparam name="T5">The type of the value tuple's fifth element.</typeparam>
		/// <param name="item5">The value of the value tuple tuple's fifth element.</param>
		/// <typeparam name="T6">The type of the value tuple's sixth element.</typeparam>
		/// <param name="item6">The value of the value tuple tuple's sixth element.</param>
		/// <typeparam name="T7">The type of the value tuple's seventh element.</typeparam>
		/// <param name="item7">The value of the value tuple tuple's seventh element.</param>
		/// <typeparam name="T8">The type of the value tuple's eigth element.</typeparam>
		/// <param name="item8">The value of the value tuple tuple's eigth element.</param>
		/// <returns>A new <see cref="ValueTuple{T1, T2, T3, T4, T5, T6, T7, T8}" /> where the last item is a <see cref="ValueTuple{T1}" /> containing the last item.</returns>
		public static ValueTuple<T1, T2, T3, T4, T5, T6, T7, ValueTuple<T8>> Create<T1, T2, T3, T4, T5, T6, T7, T8>(T1 item1, T2 item2, T3 item3, T4 item4, T5 item5, T6 item6, T7 item7, T8 item8) {
			return new ValueTuple<T1, T2, T3, T4, T5, T6, T7, ValueTuple<T8>>(item1, item2, item3, item4, item5, item6, item7, new ValueTuple<T8>(item8));
		}
	}

	/// <summary>Represents a value tuple with 1 component.</summary>
	/// <typeparam name="T1">The type of the value tuple's first element.</typeparam>
	[Serializable]
	public struct ValueTuple<T1> : IEquatable<ValueTuple<T1>>, IStructuralEquatable, IStructuralComparable, IComparable, IComparable<ValueTuple<T1>>
	{
		/// <summary>The first item in this <see cref="ValueTuple{T1}" />.</summary>
		public T1 Item1;

		/// <summary>Initializes a new value tuple.</summary>
		/// <param name="item1">The value of the first item.</param>
		public ValueTuple(T1 item1) {
			this.Item1 = item1;
		}

		/// <inheritdoc />
        public override bool Equals(object obj) {
            return obj is ValueTuple<T1> other && this.Equals(other);
        }

		/// <inheritdoc />
		public bool Equals(ValueTuple<T1> other) {
            return EqualityComparer<T1>.Default.Equals(this.Item1, other.Item1);
        }

		/// <inheritdoc />
		public bool Equals(object other, IEqualityComparer comparer) {
            if (!(other is ValueTuple<T1> otherTuple)) {
				return false;
			}

			return comparer.Equals(this.Item1, otherTuple.Item1);
        }

		/// <inheritdoc />
        public int CompareTo(object obj) {
			return obj is ValueTuple<T1> other ? this.CompareTo(other) : throw new ArgumentException();
		}

		/// <inheritdoc />
        public int CompareTo(ValueTuple<T1> other) {
			return Comparer<T1>.Default.Compare(this.Item1, other.Item1);		
        }

		/// <inheritdoc />
		public int CompareTo(object obj, IComparer comparer) {
			if (!(obj is ValueTuple<T1> other)) {
				throw new ArgumentException();
			}

			return comparer.Compare(this.Item1, other.Item1);		
        }

		/// <inheritdoc />
		public override int GetHashCode() {
			return ValueTuple.CombineHashes(this.Item1?.GetHashCode() ?? 0);
		}

		/// <inheritdoc />
        public int GetHashCode(IEqualityComparer comparer) {
            return ValueTuple.CombineHashes(comparer.GetHashCode(this.Item1));
        }
	}

	/// <summary>Represents a value tuple with 2 components.</summary>
	/// <typeparam name="T1">The type of the value tuple's first element.</typeparam>
	/// <typeparam name="T2">The type of the value tuple's second element.</typeparam>
	[Serializable]
	public struct ValueTuple<T1, T2> : IEquatable<ValueTuple<T1, T2>>, IStructuralEquatable, IStructuralComparable, IComparable, IComparable<ValueTuple<T1, T2>>
	{
		/// <summary>The first item in this <see cref="ValueTuple{T1, T2}" />.</summary>
		public T1 Item1;

		/// <summary>The second item in this <see cref="ValueTuple{T1, T2}" />.</summary>
		public T2 Item2;

		/// <summary>Initializes a new value tuple.</summary>
		/// <param name="item1">The value of the first item.</param>
		/// <param name="item2">The value of the second item.</param>
		public ValueTuple(T1 item1, T2 item2) {
			this.Item1 = item1;
			this.Item2 = item2;
		}

		/// <inheritdoc />
        public override bool Equals(object obj) {
            return obj is ValueTuple<T1, T2> other && this.Equals(other);
        }

		/// <inheritdoc />
		public bool Equals(ValueTuple<T1, T2> other) {
            return EqualityComparer<T1>.Default.Equals(this.Item1, other.Item1)
                && EqualityComparer<T2>.Default.Equals(this.Item2, other.Item2);
        }

		/// <inheritdoc />
		public bool Equals(object other, IEqualityComparer comparer) {
            if (!(other is ValueTuple<T1, T2> otherTuple)) {
				return false;
			}

			return comparer.Equals(this.Item1, otherTuple.Item1)
                && comparer.Equals(this.Item2, otherTuple.Item2);
        }

		/// <inheritdoc />
        public int CompareTo(object obj) {
			return obj is ValueTuple<T1, T2> other ? this.CompareTo(other) : throw new ArgumentException();
		}

		/// <inheritdoc />
        public int CompareTo(ValueTuple<T1, T2> other) {
			int result = Comparer<T1>.Default.Compare(this.Item1, other.Item1);
			if (result != 0) {
				return result;
			}

			return Comparer<T2>.Default.Compare(this.Item2, other.Item2);		
        }

		/// <inheritdoc />
		public int CompareTo(object obj, IComparer comparer) {
			if (!(obj is ValueTuple<T1, T2> other)) {
				throw new ArgumentException();
			}

			int result = comparer.Compare(this.Item1, other.Item1);
			if (result != 0) {
				return result;
			}

			return comparer.Compare(this.Item2, other.Item2);		
        }

		/// <inheritdoc />
		public override int GetHashCode() {
			return ValueTuple.CombineHashes(this.Item1?.GetHashCode() ?? 0, this.Item2?.GetHashCode() ?? 0);
		}

		/// <inheritdoc />
        public int GetHashCode(IEqualityComparer comparer) {
            return ValueTuple.CombineHashes(comparer.GetHashCode(this.Item1), comparer.GetHashCode(this.Item2));
        }
	}

	/// <summary>Represents a value tuple with 3 components.</summary>
	/// <typeparam name="T1">The type of the value tuple's first element.</typeparam>
	/// <typeparam name="T2">The type of the value tuple's second element.</typeparam>
	/// <typeparam name="T3">The type of the value tuple's third element.</typeparam>
	[Serializable]
	public struct ValueTuple<T1, T2, T3> : IEquatable<ValueTuple<T1, T2, T3>>, IStructuralEquatable, IStructuralComparable, IComparable, IComparable<ValueTuple<T1, T2, T3>>
	{
		/// <summary>The first item in this <see cref="ValueTuple{T1, T2, T3}" />.</summary>
		public T1 Item1;

		/// <summary>The second item in this <see cref="ValueTuple{T1, T2, T3}" />.</summary>
		public T2 Item2;

		/// <summary>The third item in this <see cref="ValueTuple{T1, T2, T3}" />.</summary>
		public T3 Item3;

		/// <summary>Initializes a new value tuple.</summary>
		/// <param name="item1">The value of the first item.</param>
		/// <param name="item2">The value of the second item.</param>
		/// <param name="item3">The value of the third item.</param>
		public ValueTuple(T1 item1, T2 item2, T3 item3) {
			this.Item1 = item1;
			this.Item2 = item2;
			this.Item3 = item3;
		}

		/// <inheritdoc />
        public override bool Equals(object obj) {
            return obj is ValueTuple<T1, T2, T3> other && this.Equals(other);
        }

		/// <inheritdoc />
		public bool Equals(ValueTuple<T1, T2, T3> other) {
            return EqualityComparer<T1>.Default.Equals(this.Item1, other.Item1)
                && EqualityComparer<T2>.Default.Equals(this.Item2, other.Item2)
                && EqualityComparer<T3>.Default.Equals(this.Item3, other.Item3);
        }

		/// <inheritdoc />
		public bool Equals(object other, IEqualityComparer comparer) {
            if (!(other is ValueTuple<T1, T2, T3> otherTuple)) {
				return false;
			}

			return comparer.Equals(this.Item1, otherTuple.Item1)
                && comparer.Equals(this.Item2, otherTuple.Item2)
                && comparer.Equals(this.Item3, otherTuple.Item3);
        }

		/// <inheritdoc />
        public int CompareTo(object obj) {
			return obj is ValueTuple<T1, T2, T3> other ? this.CompareTo(other) : throw new ArgumentException();
		}

		/// <inheritdoc />
        public int CompareTo(ValueTuple<T1, T2, T3> other) {
			int result = Comparer<T1>.Default.Compare(this.Item1, other.Item1);
			if (result != 0) {
				return result;
			}

			result = Comparer<T2>.Default.Compare(this.Item2, other.Item2);
			if (result != 0) {
				return result;
			}

			return Comparer<T3>.Default.Compare(this.Item3, other.Item3);		
        }

		/// <inheritdoc />
		public int CompareTo(object obj, IComparer comparer) {
			if (!(obj is ValueTuple<T1, T2, T3> other)) {
				throw new ArgumentException();
			}

			int result = comparer.Compare(this.Item1, other.Item1);
			if (result != 0) {
				return result;
			}

			result = comparer.Compare(this.Item2, other.Item2);
			if (result != 0) {
				return result;
			}

			return comparer.Compare(this.Item3, other.Item3);		
        }

		/// <inheritdoc />
		public override int GetHashCode() {
			return ValueTuple.CombineHashes(this.Item1?.GetHashCode() ?? 0, this.Item2?.GetHashCode() ?? 0, this.Item3?.GetHashCode() ?? 0);
		}

		/// <inheritdoc />
        public int GetHashCode(IEqualityComparer comparer) {
            return ValueTuple.CombineHashes(comparer.GetHashCode(this.Item1), comparer.GetHashCode(this.Item2), comparer.GetHashCode(this.Item3));
        }
	}

	/// <summary>Represents a value tuple with 4 components.</summary>
	/// <typeparam name="T1">The type of the value tuple's first element.</typeparam>
	/// <typeparam name="T2">The type of the value tuple's second element.</typeparam>
	/// <typeparam name="T3">The type of the value tuple's third element.</typeparam>
	/// <typeparam name="T4">The type of the value tuple's fourth element.</typeparam>
	[Serializable]
	public struct ValueTuple<T1, T2, T3, T4> : IEquatable<ValueTuple<T1, T2, T3, T4>>, IStructuralEquatable, IStructuralComparable, IComparable, IComparable<ValueTuple<T1, T2, T3, T4>>
	{
		/// <summary>The first item in this <see cref="ValueTuple{T1, T2, T3, T4}" />.</summary>
		public T1 Item1;

		/// <summary>The second item in this <see cref="ValueTuple{T1, T2, T3, T4}" />.</summary>
		public T2 Item2;

		/// <summary>The third item in this <see cref="ValueTuple{T1, T2, T3, T4}" />.</summary>
		public T3 Item3;

		/// <summary>The fourth item in this <see cref="ValueTuple{T1, T2, T3, T4}" />.</summary>
		public T4 Item4;

		/// <summary>Initializes a new value tuple.</summary>
		/// <param name="item1">The value of the first item.</param>
		/// <param name="item2">The value of the second item.</param>
		/// <param name="item3">The value of the third item.</param>
		/// <param name="item4">The value of the fourth item.</param>
		public ValueTuple(T1 item1, T2 item2, T3 item3, T4 item4) {
			this.Item1 = item1;
			this.Item2 = item2;
			this.Item3 = item3;
			this.Item4 = item4;
		}

		/// <inheritdoc />
        public override bool Equals(object obj) {
            return obj is ValueTuple<T1, T2, T3, T4> other && this.Equals(other);
        }

		/// <inheritdoc />
		public bool Equals(ValueTuple<T1, T2, T3, T4> other) {
            return EqualityComparer<T1>.Default.Equals(this.Item1, other.Item1)
                && EqualityComparer<T2>.Default.Equals(this.Item2, other.Item2)
                && EqualityComparer<T3>.Default.Equals(this.Item3, other.Item3)
                && EqualityComparer<T4>.Default.Equals(this.Item4, other.Item4);
        }

		/// <inheritdoc />
		public bool Equals(object other, IEqualityComparer comparer) {
            if (!(other is ValueTuple<T1, T2, T3, T4> otherTuple)) {
				return false;
			}

			return comparer.Equals(this.Item1, otherTuple.Item1)
                && comparer.Equals(this.Item2, otherTuple.Item2)
                && comparer.Equals(this.Item3, otherTuple.Item3)
                && comparer.Equals(this.Item4, otherTuple.Item4);
        }

		/// <inheritdoc />
        public int CompareTo(object obj) {
			return obj is ValueTuple<T1, T2, T3, T4> other ? this.CompareTo(other) : throw new ArgumentException();
		}

		/// <inheritdoc />
        public int CompareTo(ValueTuple<T1, T2, T3, T4> other) {
			int result = Comparer<T1>.Default.Compare(this.Item1, other.Item1);
			if (result != 0) {
				return result;
			}

			result = Comparer<T2>.Default.Compare(this.Item2, other.Item2);
			if (result != 0) {
				return result;
			}

			result = Comparer<T3>.Default.Compare(this.Item3, other.Item3);
			if (result != 0) {
				return result;
			}

			return Comparer<T4>.Default.Compare(this.Item4, other.Item4);		
        }

		/// <inheritdoc />
		public int CompareTo(object obj, IComparer comparer) {
			if (!(obj is ValueTuple<T1, T2, T3, T4> other)) {
				throw new ArgumentException();
			}

			int result = comparer.Compare(this.Item1, other.Item1);
			if (result != 0) {
				return result;
			}

			result = comparer.Compare(this.Item2, other.Item2);
			if (result != 0) {
				return result;
			}

			result = comparer.Compare(this.Item3, other.Item3);
			if (result != 0) {
				return result;
			}

			return comparer.Compare(this.Item4, other.Item4);		
        }

		/// <inheritdoc />
		public override int GetHashCode() {
			return ValueTuple.CombineHashes(this.Item1?.GetHashCode() ?? 0, this.Item2?.GetHashCode() ?? 0, this.Item3?.GetHashCode() ?? 0, this.Item4?.GetHashCode() ?? 0);
		}

		/// <inheritdoc />
        public int GetHashCode(IEqualityComparer comparer) {
            return ValueTuple.CombineHashes(comparer.GetHashCode(this.Item1), comparer.GetHashCode(this.Item2), comparer.GetHashCode(this.Item3), comparer.GetHashCode(this.Item4));
        }
	}

	/// <summary>Represents a value tuple with 5 components.</summary>
	/// <typeparam name="T1">The type of the value tuple's first element.</typeparam>
	/// <typeparam name="T2">The type of the value tuple's second element.</typeparam>
	/// <typeparam name="T3">The type of the value tuple's third element.</typeparam>
	/// <typeparam name="T4">The type of the value tuple's fourth element.</typeparam>
	/// <typeparam name="T5">The type of the value tuple's fifth element.</typeparam>
	[Serializable]
	public struct ValueTuple<T1, T2, T3, T4, T5> : IEquatable<ValueTuple<T1, T2, T3, T4, T5>>, IStructuralEquatable, IStructuralComparable, IComparable, IComparable<ValueTuple<T1, T2, T3, T4, T5>>
	{
		/// <summary>The first item in this <see cref="ValueTuple{T1, T2, T3, T4, T5}" />.</summary>
		public T1 Item1;

		/// <summary>The second item in this <see cref="ValueTuple{T1, T2, T3, T4, T5}" />.</summary>
		public T2 Item2;

		/// <summary>The third item in this <see cref="ValueTuple{T1, T2, T3, T4, T5}" />.</summary>
		public T3 Item3;

		/// <summary>The fourth item in this <see cref="ValueTuple{T1, T2, T3, T4, T5}" />.</summary>
		public T4 Item4;

		/// <summary>The fifth item in this <see cref="ValueTuple{T1, T2, T3, T4, T5}" />.</summary>
		public T5 Item5;

		/// <summary>Initializes a new value tuple.</summary>
		/// <param name="item1">The value of the first item.</param>
		/// <param name="item2">The value of the second item.</param>
		/// <param name="item3">The value of the third item.</param>
		/// <param name="item4">The value of the fourth item.</param>
		/// <param name="item5">The value of the fifth item.</param>
		public ValueTuple(T1 item1, T2 item2, T3 item3, T4 item4, T5 item5) {
			this.Item1 = item1;
			this.Item2 = item2;
			this.Item3 = item3;
			this.Item4 = item4;
			this.Item5 = item5;
		}

		/// <inheritdoc />
        public override bool Equals(object obj) {
            return obj is ValueTuple<T1, T2, T3, T4, T5> other && this.Equals(other);
        }

		/// <inheritdoc />
		public bool Equals(ValueTuple<T1, T2, T3, T4, T5> other) {
            return EqualityComparer<T1>.Default.Equals(this.Item1, other.Item1)
                && EqualityComparer<T2>.Default.Equals(this.Item2, other.Item2)
                && EqualityComparer<T3>.Default.Equals(this.Item3, other.Item3)
                && EqualityComparer<T4>.Default.Equals(this.Item4, other.Item4)
                && EqualityComparer<T5>.Default.Equals(this.Item5, other.Item5);
        }

		/// <inheritdoc />
		public bool Equals(object other, IEqualityComparer comparer) {
            if (!(other is ValueTuple<T1, T2, T3, T4, T5> otherTuple)) {
				return false;
			}

			return comparer.Equals(this.Item1, otherTuple.Item1)
                && comparer.Equals(this.Item2, otherTuple.Item2)
                && comparer.Equals(this.Item3, otherTuple.Item3)
                && comparer.Equals(this.Item4, otherTuple.Item4)
                && comparer.Equals(this.Item5, otherTuple.Item5);
        }

		/// <inheritdoc />
        public int CompareTo(object obj) {
			return obj is ValueTuple<T1, T2, T3, T4, T5> other ? this.CompareTo(other) : throw new ArgumentException();
		}

		/// <inheritdoc />
        public int CompareTo(ValueTuple<T1, T2, T3, T4, T5> other) {
			int result = Comparer<T1>.Default.Compare(this.Item1, other.Item1);
			if (result != 0) {
				return result;
			}

			result = Comparer<T2>.Default.Compare(this.Item2, other.Item2);
			if (result != 0) {
				return result;
			}

			result = Comparer<T3>.Default.Compare(this.Item3, other.Item3);
			if (result != 0) {
				return result;
			}

			result = Comparer<T4>.Default.Compare(this.Item4, other.Item4);
			if (result != 0) {
				return result;
			}

			return Comparer<T5>.Default.Compare(this.Item5, other.Item5);		
        }

		/// <inheritdoc />
		public int CompareTo(object obj, IComparer comparer) {
			if (!(obj is ValueTuple<T1, T2, T3, T4, T5> other)) {
				throw new ArgumentException();
			}

			int result = comparer.Compare(this.Item1, other.Item1);
			if (result != 0) {
				return result;
			}

			result = comparer.Compare(this.Item2, other.Item2);
			if (result != 0) {
				return result;
			}

			result = comparer.Compare(this.Item3, other.Item3);
			if (result != 0) {
				return result;
			}

			result = comparer.Compare(this.Item4, other.Item4);
			if (result != 0) {
				return result;
			}

			return comparer.Compare(this.Item5, other.Item5);		
        }

		/// <inheritdoc />
		public override int GetHashCode() {
			return ValueTuple.CombineHashes(this.Item1?.GetHashCode() ?? 0, this.Item2?.GetHashCode() ?? 0, this.Item3?.GetHashCode() ?? 0, this.Item4?.GetHashCode() ?? 0, this.Item5?.GetHashCode() ?? 0);
		}

		/// <inheritdoc />
        public int GetHashCode(IEqualityComparer comparer) {
            return ValueTuple.CombineHashes(comparer.GetHashCode(this.Item1), comparer.GetHashCode(this.Item2), comparer.GetHashCode(this.Item3), comparer.GetHashCode(this.Item4), comparer.GetHashCode(this.Item5));
        }
	}

	/// <summary>Represents a value tuple with 6 components.</summary>
	/// <typeparam name="T1">The type of the value tuple's first element.</typeparam>
	/// <typeparam name="T2">The type of the value tuple's second element.</typeparam>
	/// <typeparam name="T3">The type of the value tuple's third element.</typeparam>
	/// <typeparam name="T4">The type of the value tuple's fourth element.</typeparam>
	/// <typeparam name="T5">The type of the value tuple's fifth element.</typeparam>
	/// <typeparam name="T6">The type of the value tuple's sixth element.</typeparam>
	[Serializable]
	public struct ValueTuple<T1, T2, T3, T4, T5, T6> : IEquatable<ValueTuple<T1, T2, T3, T4, T5, T6>>, IStructuralEquatable, IStructuralComparable, IComparable, IComparable<ValueTuple<T1, T2, T3, T4, T5, T6>>
	{
		/// <summary>The first item in this <see cref="ValueTuple{T1, T2, T3, T4, T5, T6}" />.</summary>
		public T1 Item1;

		/// <summary>The second item in this <see cref="ValueTuple{T1, T2, T3, T4, T5, T6}" />.</summary>
		public T2 Item2;

		/// <summary>The third item in this <see cref="ValueTuple{T1, T2, T3, T4, T5, T6}" />.</summary>
		public T3 Item3;

		/// <summary>The fourth item in this <see cref="ValueTuple{T1, T2, T3, T4, T5, T6}" />.</summary>
		public T4 Item4;

		/// <summary>The fifth item in this <see cref="ValueTuple{T1, T2, T3, T4, T5, T6}" />.</summary>
		public T5 Item5;

		/// <summary>The sixth item in this <see cref="ValueTuple{T1, T2, T3, T4, T5, T6}" />.</summary>
		public T6 Item6;

		/// <summary>Initializes a new value tuple.</summary>
		/// <param name="item1">The value of the first item.</param>
		/// <param name="item2">The value of the second item.</param>
		/// <param name="item3">The value of the third item.</param>
		/// <param name="item4">The value of the fourth item.</param>
		/// <param name="item5">The value of the fifth item.</param>
		/// <param name="item6">The value of the sixth item.</param>
		public ValueTuple(T1 item1, T2 item2, T3 item3, T4 item4, T5 item5, T6 item6) {
			this.Item1 = item1;
			this.Item2 = item2;
			this.Item3 = item3;
			this.Item4 = item4;
			this.Item5 = item5;
			this.Item6 = item6;
		}

		/// <inheritdoc />
        public override bool Equals(object obj) {
            return obj is ValueTuple<T1, T2, T3, T4, T5, T6> other && this.Equals(other);
        }

		/// <inheritdoc />
		public bool Equals(ValueTuple<T1, T2, T3, T4, T5, T6> other) {
            return EqualityComparer<T1>.Default.Equals(this.Item1, other.Item1)
                && EqualityComparer<T2>.Default.Equals(this.Item2, other.Item2)
                && EqualityComparer<T3>.Default.Equals(this.Item3, other.Item3)
                && EqualityComparer<T4>.Default.Equals(this.Item4, other.Item4)
                && EqualityComparer<T5>.Default.Equals(this.Item5, other.Item5)
                && EqualityComparer<T6>.Default.Equals(this.Item6, other.Item6);
        }

		/// <inheritdoc />
		public bool Equals(object other, IEqualityComparer comparer) {
            if (!(other is ValueTuple<T1, T2, T3, T4, T5, T6> otherTuple)) {
				return false;
			}

			return comparer.Equals(this.Item1, otherTuple.Item1)
                && comparer.Equals(this.Item2, otherTuple.Item2)
                && comparer.Equals(this.Item3, otherTuple.Item3)
                && comparer.Equals(this.Item4, otherTuple.Item4)
                && comparer.Equals(this.Item5, otherTuple.Item5)
                && comparer.Equals(this.Item6, otherTuple.Item6);
        }

		/// <inheritdoc />
        public int CompareTo(object obj) {
			return obj is ValueTuple<T1, T2, T3, T4, T5, T6> other ? this.CompareTo(other) : throw new ArgumentException();
		}

		/// <inheritdoc />
        public int CompareTo(ValueTuple<T1, T2, T3, T4, T5, T6> other) {
			int result = Comparer<T1>.Default.Compare(this.Item1, other.Item1);
			if (result != 0) {
				return result;
			}

			result = Comparer<T2>.Default.Compare(this.Item2, other.Item2);
			if (result != 0) {
				return result;
			}

			result = Comparer<T3>.Default.Compare(this.Item3, other.Item3);
			if (result != 0) {
				return result;
			}

			result = Comparer<T4>.Default.Compare(this.Item4, other.Item4);
			if (result != 0) {
				return result;
			}

			result = Comparer<T5>.Default.Compare(this.Item5, other.Item5);
			if (result != 0) {
				return result;
			}

			return Comparer<T6>.Default.Compare(this.Item6, other.Item6);		
        }

		/// <inheritdoc />
		public int CompareTo(object obj, IComparer comparer) {
			if (!(obj is ValueTuple<T1, T2, T3, T4, T5, T6> other)) {
				throw new ArgumentException();
			}

			int result = comparer.Compare(this.Item1, other.Item1);
			if (result != 0) {
				return result;
			}

			result = comparer.Compare(this.Item2, other.Item2);
			if (result != 0) {
				return result;
			}

			result = comparer.Compare(this.Item3, other.Item3);
			if (result != 0) {
				return result;
			}

			result = comparer.Compare(this.Item4, other.Item4);
			if (result != 0) {
				return result;
			}

			result = comparer.Compare(this.Item5, other.Item5);
			if (result != 0) {
				return result;
			}

			return comparer.Compare(this.Item6, other.Item6);		
        }

		/// <inheritdoc />
		public override int GetHashCode() {
			return ValueTuple.CombineHashes(this.Item1?.GetHashCode() ?? 0, this.Item2?.GetHashCode() ?? 0, this.Item3?.GetHashCode() ?? 0, this.Item4?.GetHashCode() ?? 0, this.Item5?.GetHashCode() ?? 0, this.Item6?.GetHashCode() ?? 0);
		}

		/// <inheritdoc />
        public int GetHashCode(IEqualityComparer comparer) {
            return ValueTuple.CombineHashes(comparer.GetHashCode(this.Item1), comparer.GetHashCode(this.Item2), comparer.GetHashCode(this.Item3), comparer.GetHashCode(this.Item4), comparer.GetHashCode(this.Item5), comparer.GetHashCode(this.Item6));
        }
	}

	/// <summary>Represents a value tuple with 7 components.</summary>
	/// <typeparam name="T1">The type of the value tuple's first element.</typeparam>
	/// <typeparam name="T2">The type of the value tuple's second element.</typeparam>
	/// <typeparam name="T3">The type of the value tuple's third element.</typeparam>
	/// <typeparam name="T4">The type of the value tuple's fourth element.</typeparam>
	/// <typeparam name="T5">The type of the value tuple's fifth element.</typeparam>
	/// <typeparam name="T6">The type of the value tuple's sixth element.</typeparam>
	/// <typeparam name="T7">The type of the value tuple's seventh element.</typeparam>
	[Serializable]
	public struct ValueTuple<T1, T2, T3, T4, T5, T6, T7> : IEquatable<ValueTuple<T1, T2, T3, T4, T5, T6, T7>>, IStructuralEquatable, IStructuralComparable, IComparable, IComparable<ValueTuple<T1, T2, T3, T4, T5, T6, T7>>
	{
		/// <summary>The first item in this <see cref="ValueTuple{T1, T2, T3, T4, T5, T6, T7}" />.</summary>
		public T1 Item1;

		/// <summary>The second item in this <see cref="ValueTuple{T1, T2, T3, T4, T5, T6, T7}" />.</summary>
		public T2 Item2;

		/// <summary>The third item in this <see cref="ValueTuple{T1, T2, T3, T4, T5, T6, T7}" />.</summary>
		public T3 Item3;

		/// <summary>The fourth item in this <see cref="ValueTuple{T1, T2, T3, T4, T5, T6, T7}" />.</summary>
		public T4 Item4;

		/// <summary>The fifth item in this <see cref="ValueTuple{T1, T2, T3, T4, T5, T6, T7}" />.</summary>
		public T5 Item5;

		/// <summary>The sixth item in this <see cref="ValueTuple{T1, T2, T3, T4, T5, T6, T7}" />.</summary>
		public T6 Item6;

		/// <summary>The seventh item in this <see cref="ValueTuple{T1, T2, T3, T4, T5, T6, T7}" />.</summary>
		public T7 Item7;

		/// <summary>Initializes a new value tuple.</summary>
		/// <param name="item1">The value of the first item.</param>
		/// <param name="item2">The value of the second item.</param>
		/// <param name="item3">The value of the third item.</param>
		/// <param name="item4">The value of the fourth item.</param>
		/// <param name="item5">The value of the fifth item.</param>
		/// <param name="item6">The value of the sixth item.</param>
		/// <param name="item7">The value of the seventh item.</param>
		public ValueTuple(T1 item1, T2 item2, T3 item3, T4 item4, T5 item5, T6 item6, T7 item7) {
			this.Item1 = item1;
			this.Item2 = item2;
			this.Item3 = item3;
			this.Item4 = item4;
			this.Item5 = item5;
			this.Item6 = item6;
			this.Item7 = item7;
		}

		/// <inheritdoc />
        public override bool Equals(object obj) {
            return obj is ValueTuple<T1, T2, T3, T4, T5, T6, T7> other && this.Equals(other);
        }

		/// <inheritdoc />
		public bool Equals(ValueTuple<T1, T2, T3, T4, T5, T6, T7> other) {
            return EqualityComparer<T1>.Default.Equals(this.Item1, other.Item1)
                && EqualityComparer<T2>.Default.Equals(this.Item2, other.Item2)
                && EqualityComparer<T3>.Default.Equals(this.Item3, other.Item3)
                && EqualityComparer<T4>.Default.Equals(this.Item4, other.Item4)
                && EqualityComparer<T5>.Default.Equals(this.Item5, other.Item5)
                && EqualityComparer<T6>.Default.Equals(this.Item6, other.Item6)
                && EqualityComparer<T7>.Default.Equals(this.Item7, other.Item7);
        }

		/// <inheritdoc />
		public bool Equals(object other, IEqualityComparer comparer) {
            if (!(other is ValueTuple<T1, T2, T3, T4, T5, T6, T7> otherTuple)) {
				return false;
			}

			return comparer.Equals(this.Item1, otherTuple.Item1)
                && comparer.Equals(this.Item2, otherTuple.Item2)
                && comparer.Equals(this.Item3, otherTuple.Item3)
                && comparer.Equals(this.Item4, otherTuple.Item4)
                && comparer.Equals(this.Item5, otherTuple.Item5)
                && comparer.Equals(this.Item6, otherTuple.Item6)
                && comparer.Equals(this.Item7, otherTuple.Item7);
        }

		/// <inheritdoc />
        public int CompareTo(object obj) {
			return obj is ValueTuple<T1, T2, T3, T4, T5, T6, T7> other ? this.CompareTo(other) : throw new ArgumentException();
		}

		/// <inheritdoc />
        public int CompareTo(ValueTuple<T1, T2, T3, T4, T5, T6, T7> other) {
			int result = Comparer<T1>.Default.Compare(this.Item1, other.Item1);
			if (result != 0) {
				return result;
			}

			result = Comparer<T2>.Default.Compare(this.Item2, other.Item2);
			if (result != 0) {
				return result;
			}

			result = Comparer<T3>.Default.Compare(this.Item3, other.Item3);
			if (result != 0) {
				return result;
			}

			result = Comparer<T4>.Default.Compare(this.Item4, other.Item4);
			if (result != 0) {
				return result;
			}

			result = Comparer<T5>.Default.Compare(this.Item5, other.Item5);
			if (result != 0) {
				return result;
			}

			result = Comparer<T6>.Default.Compare(this.Item6, other.Item6);
			if (result != 0) {
				return result;
			}

			return Comparer<T7>.Default.Compare(this.Item7, other.Item7);		
        }

		/// <inheritdoc />
		public int CompareTo(object obj, IComparer comparer) {
			if (!(obj is ValueTuple<T1, T2, T3, T4, T5, T6, T7> other)) {
				throw new ArgumentException();
			}

			int result = comparer.Compare(this.Item1, other.Item1);
			if (result != 0) {
				return result;
			}

			result = comparer.Compare(this.Item2, other.Item2);
			if (result != 0) {
				return result;
			}

			result = comparer.Compare(this.Item3, other.Item3);
			if (result != 0) {
				return result;
			}

			result = comparer.Compare(this.Item4, other.Item4);
			if (result != 0) {
				return result;
			}

			result = comparer.Compare(this.Item5, other.Item5);
			if (result != 0) {
				return result;
			}

			result = comparer.Compare(this.Item6, other.Item6);
			if (result != 0) {
				return result;
			}

			return comparer.Compare(this.Item7, other.Item7);		
        }

		/// <inheritdoc />
		public override int GetHashCode() {
			return ValueTuple.CombineHashes(this.Item1?.GetHashCode() ?? 0, this.Item2?.GetHashCode() ?? 0, this.Item3?.GetHashCode() ?? 0, this.Item4?.GetHashCode() ?? 0, this.Item5?.GetHashCode() ?? 0, this.Item6?.GetHashCode() ?? 0, this.Item7?.GetHashCode() ?? 0);
		}

		/// <inheritdoc />
        public int GetHashCode(IEqualityComparer comparer) {
            return ValueTuple.CombineHashes(comparer.GetHashCode(this.Item1), comparer.GetHashCode(this.Item2), comparer.GetHashCode(this.Item3), comparer.GetHashCode(this.Item4), comparer.GetHashCode(this.Item5), comparer.GetHashCode(this.Item6), comparer.GetHashCode(this.Item7));
        }
	}

	/// <summary>Represents a value tuple with 8 components.</summary>
	/// <typeparam name="T1">The type of the value tuple's first element.</typeparam>
	/// <typeparam name="T2">The type of the value tuple's second element.</typeparam>
	/// <typeparam name="T3">The type of the value tuple's third element.</typeparam>
	/// <typeparam name="T4">The type of the value tuple's fourth element.</typeparam>
	/// <typeparam name="T5">The type of the value tuple's fifth element.</typeparam>
	/// <typeparam name="T6">The type of the value tuple's sixth element.</typeparam>
	/// <typeparam name="T7">The type of the value tuple's seventh element.</typeparam>
	/// <typeparam name="T8">The type of the value tuple's eigth element.</typeparam>
	[Serializable]
	public struct ValueTuple<T1, T2, T3, T4, T5, T6, T7, T8> : IEquatable<ValueTuple<T1, T2, T3, T4, T5, T6, T7, T8>>, IStructuralEquatable, IStructuralComparable, IComparable, IComparable<ValueTuple<T1, T2, T3, T4, T5, T6, T7, T8>>
	{
		/// <summary>The first item in this <see cref="ValueTuple{T1, T2, T3, T4, T5, T6, T7, T8}" />.</summary>
		public T1 Item1;

		/// <summary>The second item in this <see cref="ValueTuple{T1, T2, T3, T4, T5, T6, T7, T8}" />.</summary>
		public T2 Item2;

		/// <summary>The third item in this <see cref="ValueTuple{T1, T2, T3, T4, T5, T6, T7, T8}" />.</summary>
		public T3 Item3;

		/// <summary>The fourth item in this <see cref="ValueTuple{T1, T2, T3, T4, T5, T6, T7, T8}" />.</summary>
		public T4 Item4;

		/// <summary>The fifth item in this <see cref="ValueTuple{T1, T2, T3, T4, T5, T6, T7, T8}" />.</summary>
		public T5 Item5;

		/// <summary>The sixth item in this <see cref="ValueTuple{T1, T2, T3, T4, T5, T6, T7, T8}" />.</summary>
		public T6 Item6;

		/// <summary>The seventh item in this <see cref="ValueTuple{T1, T2, T3, T4, T5, T6, T7, T8}" />.</summary>
		public T7 Item7;

		/// <summary>The eigth item in this <see cref="ValueTuple{T1, T2, T3, T4, T5, T6, T7, T8}" />.</summary>
		public T8 Item8;

		/// <summary>Initializes a new value tuple.</summary>
		/// <param name="item1">The value of the first item.</param>
		/// <param name="item2">The value of the second item.</param>
		/// <param name="item3">The value of the third item.</param>
		/// <param name="item4">The value of the fourth item.</param>
		/// <param name="item5">The value of the fifth item.</param>
		/// <param name="item6">The value of the sixth item.</param>
		/// <param name="item7">The value of the seventh item.</param>
		/// <param name="item8">The value of the eigth item.</param>
		public ValueTuple(T1 item1, T2 item2, T3 item3, T4 item4, T5 item5, T6 item6, T7 item7, T8 item8) {
			this.Item1 = item1;
			this.Item2 = item2;
			this.Item3 = item3;
			this.Item4 = item4;
			this.Item5 = item5;
			this.Item6 = item6;
			this.Item7 = item7;
			this.Item8 = item8;
		}

		/// <inheritdoc />
        public override bool Equals(object obj) {
            return obj is ValueTuple<T1, T2, T3, T4, T5, T6, T7, T8> other && this.Equals(other);
        }

		/// <inheritdoc />
		public bool Equals(ValueTuple<T1, T2, T3, T4, T5, T6, T7, T8> other) {
            return EqualityComparer<T1>.Default.Equals(this.Item1, other.Item1)
                && EqualityComparer<T2>.Default.Equals(this.Item2, other.Item2)
                && EqualityComparer<T3>.Default.Equals(this.Item3, other.Item3)
                && EqualityComparer<T4>.Default.Equals(this.Item4, other.Item4)
                && EqualityComparer<T5>.Default.Equals(this.Item5, other.Item5)
                && EqualityComparer<T6>.Default.Equals(this.Item6, other.Item6)
                && EqualityComparer<T7>.Default.Equals(this.Item7, other.Item7)
                && EqualityComparer<T8>.Default.Equals(this.Item8, other.Item8);
        }

		/// <inheritdoc />
		public bool Equals(object other, IEqualityComparer comparer) {
            if (!(other is ValueTuple<T1, T2, T3, T4, T5, T6, T7, T8> otherTuple)) {
				return false;
			}

			return comparer.Equals(this.Item1, otherTuple.Item1)
                && comparer.Equals(this.Item2, otherTuple.Item2)
                && comparer.Equals(this.Item3, otherTuple.Item3)
                && comparer.Equals(this.Item4, otherTuple.Item4)
                && comparer.Equals(this.Item5, otherTuple.Item5)
                && comparer.Equals(this.Item6, otherTuple.Item6)
                && comparer.Equals(this.Item7, otherTuple.Item7)
                && comparer.Equals(this.Item8, otherTuple.Item8);
        }

		/// <inheritdoc />
        public int CompareTo(object obj) {
			return obj is ValueTuple<T1, T2, T3, T4, T5, T6, T7, T8> other ? this.CompareTo(other) : throw new ArgumentException();
		}

		/// <inheritdoc />
        public int CompareTo(ValueTuple<T1, T2, T3, T4, T5, T6, T7, T8> other) {
			int result = Comparer<T1>.Default.Compare(this.Item1, other.Item1);
			if (result != 0) {
				return result;
			}

			result = Comparer<T2>.Default.Compare(this.Item2, other.Item2);
			if (result != 0) {
				return result;
			}

			result = Comparer<T3>.Default.Compare(this.Item3, other.Item3);
			if (result != 0) {
				return result;
			}

			result = Comparer<T4>.Default.Compare(this.Item4, other.Item4);
			if (result != 0) {
				return result;
			}

			result = Comparer<T5>.Default.Compare(this.Item5, other.Item5);
			if (result != 0) {
				return result;
			}

			result = Comparer<T6>.Default.Compare(this.Item6, other.Item6);
			if (result != 0) {
				return result;
			}

			result = Comparer<T7>.Default.Compare(this.Item7, other.Item7);
			if (result != 0) {
				return result;
			}

			return Comparer<T8>.Default.Compare(this.Item8, other.Item8);		
        }

		/// <inheritdoc />
		public int CompareTo(object obj, IComparer comparer) {
			if (!(obj is ValueTuple<T1, T2, T3, T4, T5, T6, T7, T8> other)) {
				throw new ArgumentException();
			}

			int result = comparer.Compare(this.Item1, other.Item1);
			if (result != 0) {
				return result;
			}

			result = comparer.Compare(this.Item2, other.Item2);
			if (result != 0) {
				return result;
			}

			result = comparer.Compare(this.Item3, other.Item3);
			if (result != 0) {
				return result;
			}

			result = comparer.Compare(this.Item4, other.Item4);
			if (result != 0) {
				return result;
			}

			result = comparer.Compare(this.Item5, other.Item5);
			if (result != 0) {
				return result;
			}

			result = comparer.Compare(this.Item6, other.Item6);
			if (result != 0) {
				return result;
			}

			result = comparer.Compare(this.Item7, other.Item7);
			if (result != 0) {
				return result;
			}

			return comparer.Compare(this.Item8, other.Item8);		
        }

		/// <inheritdoc />
		public override int GetHashCode() {
			return ValueTuple.CombineHashes(this.Item1?.GetHashCode() ?? 0, this.Item2?.GetHashCode() ?? 0, this.Item3?.GetHashCode() ?? 0, this.Item4?.GetHashCode() ?? 0, this.Item5?.GetHashCode() ?? 0, this.Item6?.GetHashCode() ?? 0, this.Item7?.GetHashCode() ?? 0, this.Item8?.GetHashCode() ?? 0);
		}

		/// <inheritdoc />
        public int GetHashCode(IEqualityComparer comparer) {
            return ValueTuple.CombineHashes(comparer.GetHashCode(this.Item1), comparer.GetHashCode(this.Item2), comparer.GetHashCode(this.Item3), comparer.GetHashCode(this.Item4), comparer.GetHashCode(this.Item5), comparer.GetHashCode(this.Item6), comparer.GetHashCode(this.Item7), comparer.GetHashCode(this.Item8));
        }
	}
}
